---
- name: Get devices
  hosts: test
  connection: local
  gather_facts: False

  tasks:

   - include_vars: vars.yml 

   - ios_facts:
       gather_subset: 
         - interfaces
       provider:
         host: "{{inventory_hostname}}"
         username: "{{username}}"
         password: "{{password}}"
     register: result
 
   - debug: var=result.ansible_facts.ansible_net_neighbors
